apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: asm-k8s
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: asm:kubernetes-observer
subjects:
- kind: ServiceAccount
  name: asm-k8s-account
  namespace: asm-sample