apiVersion: v1
imagePullSecrets:
- name: asm-k8s-account-dockercfg-q2n5t
kind: ServiceAccount
metadata:
  name: asm-k8s-account
secrets:
- name: asm-k8s-account-token-2qh6p
- name: asm-k8s-account-dockercfg-q2n5t